trying change to use ESM package https://docusaurus.io/docs/next/configuration because:
 Error: Docusaurus server-side rendering could not render static page with path /docs/chap-6/g-b-the-loop-facility because of error: window is not defined
  It looks like you are using code that should run on the client-side only.
  To get around it, try using `<BrowserOnly>` (https://docusaurus.io/docs/docusaurus-core/#browseronly) or `ExecutionEnvironment` (https://docusaurus.io/docs/docusaurus-core/#executionenvironment).
  It might also require to wrap your client code in `useEffect` hook and/or import a third-party library dynamically (if any).